services:
  postgres:
    image: postgres:16-alpine
    container_name: hoian_blog_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hoian_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_hoian_blog:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hoian_blog"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata_hoian_blog:
